version: '3.9'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: term_keeper_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    healthcheck:
      test: "mysqladmin ping -h localhost -u root -p$$MYSQL_ROOT_PASSWORD"
      interval: 3s
      timeout: 5s
      retries: 10
      start_period: 5s
    restart: always
    volumes:
      - mysql-data:/var/lib/mysql
      - ./external-apps/db/:/docker-entrypoint-initdb.d
      - ./etc/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    networks:
      - mysql-network

  mysql-cli:
    image: mysql:8.0
    command: mysql -hmysql -uuser -ppassword --default-character-set=utf8mb4 term_keeper_db
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - mysql-network

networks:
  mysql-network:
    driver: bridge

volumes:
  mysql-data:
